In [2]:
import pandas as pd


data = pd.read_csv("Train.csv")
data


URL  URL_LENGTH  NUMBER_SPECIAL_CHARACTERS     CHARSET  \
0     B0_2314          16                          6       UTF-8   
1      B0_911          16                          6    us-ascii   
2      B0_113          17                          6  ISO-8859-1   
3      B0_403          17                          6       UTF-8   
4     B0_2064          18                          7       UTF-8   
...       ...         ...                        ...         ...   
1426    M4_45         194                         17       UTF-8   
1427    M4_48         194                         16       UTF-8   
1428   B0_162         201                         34       utf-8   
1429  B0_1152         234                         34  ISO-8859-1   
1430   B0_676         249                         40       utf-8   

                      SERVER  CONTENT_LENGTH WHOIS_COUNTRY WHOIS_STATEPRO  \
0              Apache/2.4.10         15087.0          None           None   
1      Microsoft-HTTPAPI/2.0           324.0          None           None   
2                      nginx           162.0            US             AK   
3                       None        124140.0            US             TX   
4                      nginx             NaN            SC           Mahe   
...                      ...             ...           ...            ...   
1426                  Apache             NaN            ES      Barcelona   
1427                  Apache             NaN            ES      Barcelona   
1428  Apache/2.2.16 (Debian)          8904.0            US             FL   
1429        cloudflare-nginx             NaN            US             CA   
1430       Microsoft-IIS/8.5         24435.0            US      Wisconsin   

        WHOIS_REGDATE WHOIS_UPDATED_DATE  ...  DIST_REMOTE_TCP_PORT  \
0                None               None  ...                     7   
1                None               None  ...                     0   
2      7/10/1997 4:00    12/09/2013 0:45  ...                    22   
3     12/05/1996 0:00    11/04/2017 0:00  ...                     2   
4     3/08/2016 14:30     3/10/2016 3:45  ...                     6   
...               ...                ...  ...                   ...   
1426  17/09/2008 0:00     2/09/2016 0:00  ...                     0   
1427  17/09/2008 0:00     2/09/2016 0:00  ...                     0   
1428  15/02/1999 0:00    15/07/2015 0:00  ...                     2   
1429   1/04/1998 0:00     9/12/2016 0:00  ...                     0   
1430  14/11/2008 0:00    20/11/2013 0:00  ...                     6   

      REMOTE_IPS  APP_BYTES  SOURCE_APP_PACKETS  REMOTE_APP_PACKETS  \
0              4       1230                  17                  19   
1              0          0                   0                   0   
2              3       3812                  39                  37   
3              5       4278                  61                  62   
4              9        894                  11                  13   
...          ...        ...                 ...                 ...   
1426           0          0                   0                   3   
1427           0          0                   0                   3   
1428           6       6631                  87                  89   
1429           0          0                   0                   0   
1430          11       2314                  25                  28   

      SOURCE_APP_BYTES  REMOTE_APP_BYTES  APP_PACKETS  DNS_QUERY_TIMES  Type  
0                 1265              1230           17              0.0     0  
1                    0                 0            0              0.0     0  
2                18784              4380           39              8.0     0  
3               129889              4586           61              4.0     0  
4                  838               894           11              0.0     0  
...                ...               ...          ...              ...   ...  
1426     

In [39]:
from sklearn.preprocessing import OneHotEncoder

data["CHARSET"]= data["CHARSET"].apply(lambda x: x.upper())
#list(X.value_counts().index)
index  = 0
array = []
for name in list(data["CHARSET"].value_counts().index):
    array.append([name, index])
    index += 1

CHARSET_enc = OneHotEncoder(drop='first').fit(array)
CHARSET_enc.categories_
CHARSET_enc.transform(array).toarray()

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

X= data["SERVER"]

index  = 0
array = []
for name in list(X.value_counts().index):
    array.append([name, index])
    index += 1

SERVER_enc = OneHotEncoder(drop='first').fit(array)
SERVER_enc.categories_
SERVER_enc.transform(array).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

X= data["WHOIS_COUNTRY"]

X = X.str.replace('UNITED KINGDOM', 'UK', case= False) 

X= X.apply(lambda x: x.upper())
index  = 0
array = []
for name in list(X.value_counts().index):
    array.append([name, index])
    index += 1

COUNTRY_enc = OneHotEncoder(drop='first').fit(array)
COUNTRY_enc.categories_
COUNTRY_enc.transform(array).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [67]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

X= data["WHOIS_STATEPRO"]
X = X.str.replace('-', 'NONE', case= False) 
X = X.str.replace('--', 'NONE', case= False) 

X= X.apply(lambda x: x.upper())
index  = 0
array = []
for name in list(X.value_counts().index):
    array.append([name, index])
    index += 1

COUNTRY_enc = OneHotEncoder(drop='first').fit(array)
COUNTRY_enc.categories_
COUNTRY_enc.transform(array).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])